name: rl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - tk
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/nightly/cpu
    - torch
    - gymnasium
    - numpy
    - matplotlib

# conda remove --name rl --all
# conda env create -f environment.yml 

